In [ ]:
import pandas as pd

fines = pd.read_csv('../ex04/fines.csv')

In [48]:
fines.head(2)

      CarNumber  Refund   Fines    Make  Model  Year  Fine
0  Y163O8161RUS     2.0  3200.0    Ford  Focus  1989   NaN
1   E432XX77RUS     1.0  6500.0  Toyota  Camry  1995   NaN

In [49]:
def calc_loop(df):
    res = []
    for i in range(len(df)):
        value = df.iloc[i]['Fines'] / (df.iloc[i]['Refund'] * df.iloc[i]['Year'])
        res.append(value)
    return res

def calc_iterrows(df):
    res = []
    for _, row in df.iterrows():
        value = row['Fines'] / (row['Refund'] * row['Year'])
        res.append(value)
    return res

In [50]:
%timeit fines['Calc_loop'] = calc_loop(fines)

74.9 ms ± 3.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [51]:
%timeit fines['Calc_iterrows'] = calc_iterrows(fines)

27.9 ms ± 3.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [52]:
%timeit fines['Calc_apply'] = fines.apply(lambda row: row['Fines'] / (row['Refund'] * row['Year']), axis=1)

5.97 ms ± 507 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [53]:
%timeit fines['Calc_series'] = fines['Fines'] / (fines['Refund'] * fines['Year'])

150 μs ± 4.52 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [54]:
%timeit fines['Calc_numpy'] = fines['Fines'].values / (fines['Refund'].values * fines['Year'].values)

60.6 μs ± 1.68 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [55]:
fines.sample(2)

,CarNumber,Refund,Fines,Make,Model,Year,Fine,Calc_loop,Calc_iterrows,Calc_apply,Calc_series,Calc_numpy
610,T395KX197RUS,2.0,7600.0,Ford,Focus,2000,NaN,1.900000,1.900000,1.900000,1.900000,1.900000
879,M372CH197RUS,1.0,1000.0,Ford,Focus,2010,NaN,0.497512,0.497512,0.497512,0.497512,0.497512

In [56]:
%timeit fines[fines['CarNumber'] == 'O136HO197RUS']

214 μs ± 3.44 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [57]:
fines_idx = fines.set_index('CarNumber')

fines_idx.head(2)

,Refund,Fines,Make,Model,Year,Fine,Calc_loop,Calc_iterrows,Calc_apply,Calc_series,Calc_numpy
CarNumber,,,,,,,,,,,
Y163O8161RUS,2.0,3200.0,Ford,Focus,1989,NaN,0.804424,0.804424,0.804424,0.804424,0.804424
E432XX77RUS,1.0,6500.0,Toyota,Camry,1995,NaN,3.258145,3.258145,3.258145,3.258145,3.258145

In [58]:
%timeit fines_idx.loc['O136HO197RUS']

79.4 μs ± 4.85 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [59]:
fines.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CarNumber      930 non-null    object
 1   Refund         925 non-null    float64
 2   Fines          925 non-null    float64
 3   Make           925 non-null    object
 4   Model          913 non-null    object
 5   Year           930 non-null    int64
 6   Fine           5 non-null      float64
 7   Calc_loop      925 non-null    float64
 8   Calc_iterrows  925 non-null    float64
 9   Calc_apply     925 non-null    float64
 10  Calc_series    925 non-null    float64
 11  Calc_numpy     925 non-null    float64
dtypes: float64(8), int64(1), object(3)
memory usage: 239.8 KB

In [60]:
fines_optimized = fines.copy()

float_cols = fines_optimized.select_dtypes(include=['float64']).columns
fines_optimized[float_cols] = fines_optimized[float_cols].apply(pd.to_numeric, downcast='float')

int_cols = fines_optimized.select_dtypes(include=['int64']).columns
fines_optimized[int_cols] = fines_optimized[int_cols].apply(pd.to_numeric, downcast='integer')

fines_optimized.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CarNumber      930 non-null    object
 1   Refund         925 non-null    float32
 2   Fines          925 non-null    float32
 3   Make           925 non-null    object
 4   Model          913 non-null    object
 5   Year           930 non-null    int16
 6   Fine           5 non-null      float32
 7   Calc_loop      925 non-null    float32
 8   Calc_iterrows  925 non-null    float32
 9   Calc_apply     925 non-null    float32
 10  Calc_series    925 non-null    float32
 11  Calc_numpy     925 non-null    float32
dtypes: float32(8), int16(1), object(3)
memory usage: 205.2 KB

In [61]:
object_cols = fines.select_dtypes(include='object').columns

for col in object_cols:
    fines[col] = fines[col].astype('category')

fines.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CarNumber      930 non-null    category
 1   Refund         925 non-null    float64
 2   Fines          925 non-null    float64
 3   Make           925 non-null    category
 4   Model          913 non-null    category
 5   Year           930 non-null    int64
 6   Fine           5 non-null      float64
 7   Calc_loop      925 non-null    float64
 8   Calc_iterrows  925 non-null    float64
 9   Calc_apply     925 non-null    float64
 10  Calc_series    925 non-null    float64
 11  Calc_numpy     925 non-null    float64
dtypes: category(3), float64(8), int64(1)
memory usage: 122.9 KB

In [62]:
%reset_selective -f fines